trigger:
  - master

pool:
  vmImage: 'windows-2019'

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn
  GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'

  - task: Cache@2
    inputs:
      key: 'yarn | "$(Agent.OS)" | yarn.lock'
      restoreKeys: |
        yarn | "$(Agent.OS)"
      path: $(YARN_CACHE_FOLDER)
    displayName: Cache Yarn packages

  - script: yarn --frozen-lockfile
    displayName: 'Install dependencies'

  - script: yarn test:ci:unit
    displayName: 'Unit tests'

  - task: Cache@2
    inputs:
      key: 'gradle | "$(Agent.OS)" | **/package.json'
      restoreKeys: |
        gradle | "$(Agent.OS)"
        gradle
      path: $(GRADLE_USER_HOME)
    displayName: Configure gradle caching

  - script: yarn test:ci:e2e
    displayName: 'E2E tests'
