/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
import path from 'path';
import fs from 'fs';
import findPodfilePath from './findPodfilePath';
import findXcodeProject from './findXcodeProject';
import findPodspec from './findPodspec';
import {
  IOSProjectParams,
  IOSDependencyParams,
  IOSProjectConfig,
} from '@react-native-community/cli-types';

/**
 * Returns project config by analyzing given folder and applying some user defaults
 * when constructing final object
 */
export function projectConfig(
  folder: string,
  userConfig: IOSProjectParams,
): IOSProjectConfig | null {
  if (!userConfig) {
    return null;
  }

  const podfile = findPodfilePath(folder);

  /**
   * In certain repos, the Xcode project can
   * be generated by a tool. The only file that we can assume to exist on disk
   * is `Podfile`.
   */
  if (!podfile) {
    return null;
  }

  const sourceDir = path.dirname(podfile);

  /**
   * @todo
   * What if there are multiple `xcodeproj` found? Shall we read from a Podfile?
   */
  const xcodeProject = findXcodeProject(fs.readdirSync(sourceDir));

  return {
    sourceDir,
    xcodeProject,
  };
}

export function dependencyConfig(
  folder: string,
  userConfig: IOSDependencyParams,
) {
  return {
    podspecPath: findPodspec(folder),
    configurations: userConfig.configurations || [],
    scriptPhases: userConfig.scriptPhases || [],
  };
}
