import {getLoader, logger} from '@react-native-community/cli-tools';
import {spawn} from 'child_process';
import fs from 'fs';
import path from 'path';

function spawnPromise(
  command: string,
  args: string[],
  options: {cwd?: string; stdio?: 'inherit' | 'ignore' | 'pipe'},
): Promise<void> {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, options);
    child.on('close', (code) => {
      if (code === 0) {
        resolve();
      } else {
        reject(new Error(`Command failed: ${command} ${args.join(' ')} (exit code ${code})`));
      }
    });
    child.on('error', reject);
  });
}

export const checkGitInstallation = async (): Promise<boolean> => {
  try {
    await spawnPromise('git', ['--version'], {stdio: 'ignore'});
    return true;
  } catch {
    return false;
  }
};

export const checkIfFolderIsGitRepo = async (
  folder: string,
): Promise<boolean> => {
  try {
    await spawnPromise('git', ['rev-parse', '--is-inside-work-tree'], {
      stdio: 'ignore',
      cwd: folder,
    });
    return true;
  } catch {
    return false;
  }
};

export const createGitRepository = async (folder: string) => {
  const loader = getLoader();

  loader.start('Initializing Git repository');

  let version;

  try {
    version = JSON.parse(
      fs.readFileSync(
        path.join('node_modules/react-native/package.json'),
        'utf8',
      ),
    ).version;
  } catch {}

  try {
    await spawnPromise('git', ['init'], {cwd: folder});
    await spawnPromise('git', ['branch', '-M', 'main'], {cwd: folder});
    await spawnPromise('git', ['add', '.'], {cwd: folder});
    await spawnPromise(
      'git',
      [
        'commit',
        '-m',
        `Initial commit\n\n${
          version ? 'Generated by react-native@' + version : ''
        }`,
      ],
      {
        cwd: folder,
      },
    );
    loader.succeed();
  } catch (e) {
    loader.stop();
    logger.debug(
      'Could not create an empty Git repository, error: ',
      e as string,
    );
  }
};
