name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          ref: 'main'
          persist-credentials: false

      - name: 'Setup Node v20'
        uses: actions/setup-node@v3
        with:
          node-version: '20'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 'Prelease'
        if: 'github.event.release.prerelease'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          npx lerna version --conventional-commits --conventional-prerelease --preid alpha --yes

          npx lerna publish from-git --no-verify-access --no-changelog --yes

      - name: 'Release'
        if: '!github.event.release.prerelease'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          npx lerna version --conventional-commits --yes

          npx lerna publish from-git --no-verify-access --no-changelog --yes
